# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-30 07:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=datetime.datetime(2017, 3, 30, 7, 31, 49, 702811, tzinfo=utc), upload_to='', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=datetime.datetime(2017, 3, 30, 7, 31, 52, 912631, tzinfo=utc), upload_to='', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publications',
            name='image',
            field=models.ImageField(default=datetime.datetime(2017, 3, 30, 7, 31, 55, 354202, tzinfo=utc), upload_to='', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
            preserve_default=False,
        ),
    ]
