# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-02 16:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link_download',
            field=models.URLField(default=datetime.datetime(2017, 4, 2, 16, 28, 23, 12928, tzinfo=utc), verbose_name='\u0441\u0441\u044b\u043b\u043a\u0430 \u0434\u043b\u044f \u0441\u043a\u0430\u0447\u0438\u0432\u0430\u043d\u0438\u044f'),
            preserve_default=False,
        ),
    ]
