# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-06 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_book_link_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='country',
            field=models.CharField(choices=[('Afganistan', 'Afganistan'), ('Azerbaycan', 'Azerbaycan'), ('China', 'China'), ('Hindistan', 'Hindistan'), ('Kazakistan', 'Kazakistan'), ('Kyrgyzstan', 'Kyrgyzstan'), ('Uzbekistan', 'Uzbekistan'), ('Russia', 'Russia'), ('Tajikistan', 'Tajikistan'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan')], default=4, max_length=255, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430'),
            preserve_default=False,
        ),
    ]
