# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-06 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_news_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('uluslar', 'Uluslar arasi iliskiler'), ('ekonomi', 'ekonomi'), ('enerji', 'enerji'), ('siyaset', 'siyaset'), ('toplum', 'toplum'), ('tarim', 'TARIM'), ('hukuk', 'hukuk'), ('iletisim', 'Iletisim'), ('Guvenlik', 'Guvenlik')], max_length=100, verbose_name='\u0422\u0438\u043f \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
    ]
